#!/usr/bin/env bash
# Get domain details

displayDetails () 
{
	subdomain="$2"
	dig "$subdomain.$1" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for subDomain in "www" "lb-01" "web-01" "web-02"
do
	if [ -z "$2" ] || [ "$2" == "$subDomain" ] ;
	then
		displayDetails "$1" "$subDomain"
	fi
done
