#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Holberton School'.
#

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
