#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

default_sites="/etc/nginx/sites-available/default"
line=$(grep -Fn location $default_sites | head -1 | cut -d":" -f1)
replace_w="\\\tlocation /redirect_me {\n\t\treturn 301 http://mmesoma.tech;\n\t}\n\n"

sudo sed -i "${line}i ${replace_w}" ${default_sites}
sudo service nginx restart
