#!/usr/bin/env bash
# Run Nginx on non-root(nginx) user

pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
