#!/usr/bin/env bash

# Get the process ID of the Gunicorn master process
MASTER_PID=$(pgrep -f "gunicorn: master")

# Gracefully reload Gunicorn by sending a HUP signal to the master process
kill -HUP $MASTER_PID
